#!/usr/bin/env python3
"""Build supabase/seed.sql (idempotent upserts) from the seed JSON files.

Inputs:
  seed/mlb_teams.generated.json, seed/mlb_team_aliases.json
  seed/nfl_teams.json, seed/nfl_teams_colors.csv (nflverse, CC-BY-4.0)
  seed/mlb_venues.generated.json, seed/mlb_venue_overrides.json, seed/nfl_venues.json
Output:
  supabase/seed.sql  (run by `supabase db reset`; also safe to psql against production)

Run: python3 seed/scripts/build_seed_sql.py
"""
import csv, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SEED = os.path.join(ROOT, "seed")

def load(name):
    with open(os.path.join(SEED, name), encoding="utf8") as f:
        return json.load(f)

def q(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (dict, list)):
        return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"

def slug(s):
    out = []
    for ch in s.lower():
        if ch.isalnum():
            out.append(ch)
        elif out and out[-1] != "-":
            out.append("-")
    return "".join(out).strip("-")

lines = ["-- GENERATED by seed/scripts/build_seed_sql.py. Do not edit by hand.", "begin;", ""]

# ---------------------------------------------------------------- teams
teams = []  # (sport, provider, provider_team_id, franchise, name, city, abbr, color, active, aliases, division, home_venue_key)
mlb_alias_extra = load("mlb_team_aliases.json")
for t in load("mlb_teams.generated.json"):
    aliases = set(t["aliases"]) | set(mlb_alias_extra.get(t["provider_team_id"], []))
    aliases.add(t["name"])
    mlb_home_vid = None
    if t.get("home_venue_ids_by_season"):
        mlb_home_vid = t["home_venue_ids_by_season"][max(t["home_venue_ids_by_season"].keys())]
    teams.append(("mlb", "mlb", t["provider_team_id"], t["franchise_id"], t["name"], t["city"], t["abbreviation"], None, t["active"], aliases, t.get("division"), ("mlb_venue", mlb_home_vid), t.get("team_name")))

colors = {}
divisions = {}
colors_path = os.path.join(SEED, "nfl_teams_colors.csv")
if os.path.exists(colors_path):
    with open(colors_path, encoding="utf8") as f:
        for row in csv.DictReader(f):
            colors[row["team_abbr"]] = row.get("team_color") or None
            divisions[row["team_abbr"]] = row.get("team_division") or None

for t in load("nfl_teams.json"):
    full = f"{t['city']} {t['name']}"
    aliases = set(t["aliases"]) | {full, t["name"], t["city"], t["abbr"]}
    teams.append(("nfl", "nflverse", t["abbr"], t["franchise"], full, t["city"], t["abbr"], colors.get(t["abbr"]), t["active"], aliases, divisions.get(t["abbr"]), ("key", t.get("home_venue_key")), t["name"]))

lines.append("-- teams")
for sport, provider, pid, franchise, name, city, abbr, color, active, aliases, division, _home, nickname in teams:
    lines.append(
        "insert into public.teams (sport_id, name, city, abbreviation, primary_color_hex, active, provider, provider_team_id, franchise_id, division, nickname) values ("
        + ", ".join(q(x) for x in (sport, name, city, abbr, color, active, provider, pid, franchise, division, nickname))
        + ") on conflict (provider, provider_team_id) do update set name = excluded.name, city = excluded.city, abbreviation = excluded.abbreviation, "
        "primary_color_hex = excluded.primary_color_hex, active = excluded.active, franchise_id = excluded.franchise_id, division = excluded.division, nickname = excluded.nickname;"
    )
for sport, provider, pid, franchise, name, city, abbr, color, active, aliases, _division, _home, _nick in teams:
    for a in sorted(a for a in aliases if a):
        lines.append(
            f"insert into public.team_aliases (team_id, alias) select id, {q(a)} from public.teams where provider = {q(provider)} and provider_team_id = {q(pid)} on conflict do nothing;"
        )

# ---------------------------------------------------------------- venues
nfl = {v["key"]: v for v in load("nfl_venues.json")}
overrides = load("mlb_venue_overrides.json")
merge_by_name = overrides["merge_into_nfl_by_name"]
coords_by_name = overrides["coordinates_by_name"]
closed_by_name = overrides["closed_years_by_name"]

venues = {}
for k, v in nfl.items():
    venues[k] = {
        "key": k, "name": v["name"], "city": v.get("city"), "state": v.get("state"), "country": v.get("country"),
        "lat": v.get("lat"), "lng": v.get("lng"), "geofence_m": v.get("geofence_m", 400),
        "opened_year": v.get("opened_year"), "closed_year": v.get("closed_year"), "tz": None,
        "provider_ids": {"nflverse_stadium_ids": v["provider_ids"].get("nflverse_stadium_ids", [])},
        "sports": set(v.get("sports", ["nfl"])), "aliases": set(v.get("aliases", [])) | {v["name"]},
    }

for v in load("mlb_venues.generated.json"):
    if v["name"] == "TBD":
        continue
    names = set(v["aliases"]) | {v["name"]}
    target = None
    for n in names:
        if n in merge_by_name:
            target = merge_by_name[n]
    if target and target in venues:
        rec = venues[target]
        rec["provider_ids"]["mlb_venue_id"] = v["provider_ids"]["mlb_venue_id"]
        rec["sports"].add("mlb")
        rec["aliases"] |= names
        rec["tz"] = rec["tz"] or v.get("tz")
        continue
    key = "mlb-" + slug(v["name"]) if v["name"] else v["key"]
    if key in venues:  # two MLB venue ids with the same name (e.g. Yankee Stadium I vs II are distinct names; guard anyway)
        key = v["key"]
    rec = {
        "key": key, "name": v["name"], "city": v.get("city"), "state": v.get("state"), "country": v.get("country"),
        "lat": v.get("lat"), "lng": v.get("lng"), "geofence_m": v.get("geofence_m", 400),
        "opened_year": None, "closed_year": None, "tz": v.get("tz"),
        "provider_ids": {"mlb_venue_id": v["provider_ids"]["mlb_venue_id"]},
        "sports": {"mlb"}, "aliases": names,
    }
    for n in names:
        if n in coords_by_name:
            c = coords_by_name[n]
            rec["lat"], rec["lng"] = c["lat"], c["lng"]
            rec["city"] = c.get("city") or rec["city"]; rec["state"] = c.get("state", rec["state"])
            rec["opened_year"] = c.get("opened_year"); rec["closed_year"] = c.get("closed_year")
        if n in closed_by_name:
            rec["closed_year"] = closed_by_name[n]
    if rec["closed_year"] is None and v["last_season"] < 2024 and rec["opened_year"] is None:
        # Venue not used by MLB since before last season; mark closed for stamp styling unless we know better.
        rec["closed_year"] = v["last_season"]
    venues[key] = rec

lines.append("")
lines.append("-- venues")
for k in sorted(venues):
    v = venues[k]
    lines.append(
        "insert into public.venues (key, name, city, state, country, lat, lng, geofence_m, opened_year, closed_year, tz, provider_ids) values ("
        + ", ".join(q(x) for x in (v["key"], v["name"], v["city"], v["state"], v["country"], v["lat"], v["lng"], v["geofence_m"], v["opened_year"], v["closed_year"], v["tz"], v["provider_ids"]))
        + ") on conflict (key) do update set name = excluded.name, city = excluded.city, state = excluded.state, country = excluded.country, lat = excluded.lat, lng = excluded.lng, "
        "geofence_m = excluded.geofence_m, opened_year = excluded.opened_year, closed_year = excluded.closed_year, tz = excluded.tz, provider_ids = excluded.provider_ids;"
    )
for k in sorted(venues):
    for a in sorted(a for a in venues[k]["aliases"] if a):
        lines.append(f"insert into public.venue_aliases (venue_id, alias) select id, {q(a)} from public.venues where key = {q(k)} on conflict do nothing;")

lines.append("")
lines.append("-- team home venues")
for sport, provider, pid, franchise, name, city, abbr, color, active, aliases, _division, home, _nick in teams:
    kind, ref = home
    if ref is None:
        continue
    if kind == "key":
        cond = f"key = {q(ref)}"
    else:
        cond = f"provider_ids ->> 'mlb_venue_id' = {q(str(ref))}"
    lines.append(f"update public.teams set home_venue_id = (select id from public.venues where {cond} limit 1) where provider = {q(provider)} and provider_team_id = {q(pid)};")
lines.append("")
lines.append("select public.rebuild_curated_bucket_lists();")
lines += ["", "commit;", ""]
out = os.path.join(ROOT, "supabase", "seed.sql")
with open(out, "w", encoding="utf8") as f:
    f.write("\n".join(lines))
no_coords = [v["name"] for v in venues.values() if v["lat"] is None]
print(f"wrote {out}: {len(teams)} teams, {len(venues)} venues ({len(no_coords)} without coordinates)", file=sys.stderr)
