#!/usr/bin/env python3
"""Build supabase/seed.sql (idempotent upserts) from the seed JSON files.

Inputs:
  seed/mlb_teams.generated.json, seed/mlb_team_aliases.json
  seed/nfl_teams.json, seed/nfl_teams_colors.csv (nflverse, CC-BY-4.0)
  seed/team_colors.json (light + dark --tf/--t/--t2/--on per team; see check_team_colors.py)
  seed/mlb_venues.generated.json, seed/mlb_venue_overrides.json, seed/nfl_venues.json
  seed/venue_elevations.json (written by fill_elevations.py; see docs/verification.md)
Output:
  supabase/seed.sql  (run by `supabase db reset`; also safe to psql against production)

Run: python3 seed/scripts/build_seed_sql.py
"""
import csv, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from venues import load_elevations, merged_venues  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SEED = os.path.join(ROOT, "seed")

def load(name):
    with open(os.path.join(SEED, name), encoding="utf8") as f:
        return json.load(f)

def q(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (dict, list)):
        return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"

lines = ["-- GENERATED by seed/scripts/build_seed_sql.py. Do not edit by hand.", "begin;", ""]

# ---------------------------------------------------------------- teams
teams = []  # (sport, provider, provider_team_id, franchise, name, city, abbr, color, active, aliases, division, home_venue_key)
mlb_alias_extra = load("mlb_team_aliases.json")
for t in load("mlb_teams.generated.json"):
    aliases = set(t["aliases"]) | set(mlb_alias_extra.get(t["provider_team_id"], []))
    aliases.add(t["name"])
    mlb_home_vid = None
    if t.get("home_venue_ids_by_season"):
        mlb_home_vid = t["home_venue_ids_by_season"][max(t["home_venue_ids_by_season"].keys())]
    teams.append(("mlb", "mlb", t["provider_team_id"], t["franchise_id"], t["name"], t["city"], t["abbreviation"], None, t["active"], aliases, t.get("division"), ("mlb_venue", mlb_home_vid), t.get("team_name")))

colors = {}
divisions = {}
colors_path = os.path.join(SEED, "nfl_teams_colors.csv")
if os.path.exists(colors_path):
    with open(colors_path, encoding="utf8") as f:
        for row in csv.DictReader(f):
            colors[row["team_abbr"]] = row.get("team_color") or None
            divisions[row["team_abbr"]] = row.get("team_division") or None

for t in load("nfl_teams.json"):
    full = f"{t['city']} {t['name']}"
    aliases = set(t["aliases"]) | {full, t["name"], t["city"], t["abbr"]}
    teams.append(("nfl", "nflverse", t["abbr"], t["franchise"], full, t["city"], t["abbr"], colors.get(t["abbr"]), t["active"], aliases, divisions.get(t["abbr"]), ("key", t.get("home_venue_key")), t["name"]))

lines.append("-- teams")
for sport, provider, pid, franchise, name, city, abbr, color, active, aliases, division, _home, nickname in teams:
    lines.append(
        "insert into public.teams (sport_id, name, city, abbreviation, primary_color_hex, active, provider, provider_team_id, franchise_id, division, nickname) values ("
        + ", ".join(q(x) for x in (sport, name, city, abbr, color, active, provider, pid, franchise, division, nickname))
        + ") on conflict (provider, provider_team_id) do update set name = excluded.name, city = excluded.city, abbreviation = excluded.abbreviation, "
        "primary_color_hex = excluded.primary_color_hex, active = excluded.active, franchise_id = excluded.franchise_id, division = excluded.division, nickname = excluded.nickname;"
    )
for sport, provider, pid, franchise, name, city, abbr, color, active, aliases, _division, _home, _nick in teams:
    for a in sorted(a for a in aliases if a):
        lines.append(
            f"insert into public.team_aliases (team_id, alias) select id, {q(a)} from public.teams where provider = {q(provider)} and provider_team_id = {q(pid)} on conflict do nothing;"
        )

# ---------------------------------------------------------------- team colors
# Light and dark palettes mirroring the .t-* classes in design/reference.html (SPEC.md 8.2).
# Rows marked 'reference' are verbatim from the reference CSS; the rest are hand-tuned.
# seed/scripts/check_team_colors.py audits coverage, the verbatim rows and WCAG contrast.
palette_cols = ("fill_hex", "on_fill_hex", "primary_light_hex", "secondary_light_hex", "primary_dark_hex", "secondary_dark_hex", "source")
lines.append("")
lines.append("-- team colors")
for p in load("team_colors.json")["teams"]:
    lines.append(
        "insert into public.team_colors (team_id, " + ", ".join(palette_cols) + ") select id, "
        + ", ".join(q(p[c]) for c in palette_cols)
        + f" from public.teams where provider = {q(p['provider'])} and provider_team_id = {q(p['provider_team_id'])}"
        + " on conflict (team_id) do update set "
        + ", ".join(f"{c} = excluded.{c}" for c in palette_cols)
        + ";"
    )


# ---------------------------------------------------------------- venues
# The merge of the NFL and MLB venue files lives in venues.py so fill_elevations.py reads the very
# same set of keys and coordinates that this file writes.
venues = merged_venues()
elevations = load_elevations()

lines.append("")
lines.append("-- venues")
for k in sorted(venues):
    v = venues[k]
    lines.append(
        "insert into public.venues (key, name, city, state, country, lat, lng, geofence_m, opened_year, closed_year, tz, provider_ids, elevation_ft) values ("
        + ", ".join(q(x) for x in (v["key"], v["name"], v["city"], v["state"], v["country"], v["lat"], v["lng"], v["geofence_m"], v["opened_year"], v["closed_year"], v["tz"], v["provider_ids"], elevations.get(k)))
        + ") on conflict (key) do update set name = excluded.name, city = excluded.city, state = excluded.state, country = excluded.country, lat = excluded.lat, lng = excluded.lng, "
        "geofence_m = excluded.geofence_m, opened_year = excluded.opened_year, closed_year = excluded.closed_year, tz = excluded.tz, provider_ids = excluded.provider_ids, elevation_ft = excluded.elevation_ft;"
    )
for k in sorted(venues):
    for a in sorted(a for a in venues[k]["aliases"] if a):
        lines.append(f"insert into public.venue_aliases (venue_id, alias) select id, {q(a)} from public.venues where key = {q(k)} on conflict do nothing;")

lines.append("")
lines.append("-- venue shapes")
# The stylized stadium outlines the seals and thumbnails draw (SPEC.md 8.5). Seven shapes
# come from design/reference.html; this assigns one per venue.
#
# The rule is a venue's SPORT first, because getting that wrong is what a user sees: before
# this ran, venue_shapes was empty and every venue fell back to 'ballparkA', so Lincoln
# Financial Field was drawn as a baseball diamond. A venue that has ever hosted MLB takes a
# ballpark shape; an NFL-only venue takes a football one.
#
# Within a sport the choice is a stylized likeness, not an architectural record: ROOFED is
# "has a fixed roof, a retractable roof, or a canopy over the seating bowl", COLONNADE is
# the two neoclassical colonnaded stadiums. Both lists are by name (or alias, since MLB
# renames parks), so a venue missing from them just gets its sport's default.
MLB_SHAPES = {
    "Dodger Stadium": "dodger",
    "Wrigley Field": "wrigley",
    "Fenway Park": "wrigley",   # the reference draws Fenway with the wrigley outline
    "Oracle Park": "oracle",
}
ROOFED = {
    "AT&T Stadium", "Alamodome", "Allegiant Stadium", "Caesars Superdome", "Ford Field",
    "Georgia Dome", "Hard Rock Stadium", "Hubert H. Humphrey Metrodome", "Lucas Oil Stadium",
    "Mercedes-Benz Stadium", "Pontiac Silverdome", "RCA Dome", "Reliant Stadium",
    "Rogers Centre", "SoFi Stadium", "State Farm Stadium", "Texas Stadium",
    "The Dome at America's Center", "U.S. Bank Stadium",
}
COLONNADE = {"Soldier Field", "Los Angeles Memorial Coliseum"}

def shape_key(v):
    names = set(v["aliases"]) | {v["name"]}
    if "mlb" in v["sports"]:
        for n in names:
            if n in MLB_SHAPES:
                return MLB_SHAPES[n]
        return "ballparkA"
    if names & COLONNADE:
        return "colonnade"
    if names & ROOFED:
        return "canopy"
    return "bowl"

shape_counts = {}
for k in sorted(venues):
    key = shape_key(venues[k])
    shape_counts[key] = shape_counts.get(key, 0) + 1
    lines.append(
        f"insert into public.venue_shapes (venue_id, shape_key, source) select id, {q(key)}, 'placeholder' "
        f"from public.venues where key = {q(k)} on conflict (venue_id) do update set shape_key = excluded.shape_key;"
    )

lines.append("")
lines.append("-- team home venues")
for sport, provider, pid, franchise, name, city, abbr, color, active, aliases, _division, home, _nick in teams:
    kind, ref = home
    if ref is None:
        continue
    if kind == "key":
        cond = f"key = {q(ref)}"
    else:
        cond = f"provider_ids ->> 'mlb_venue_id' = {q(str(ref))}"
    lines.append(f"update public.teams set home_venue_id = (select id from public.venues where {cond} limit 1) where provider = {q(provider)} and provider_team_id = {q(pid)};")
lines.append("")
lines.append("select public.rebuild_curated_bucket_lists();")
lines += ["", "commit;", ""]
out = os.path.join(ROOT, "supabase", "seed.sql")
with open(out, "w", encoding="utf8") as f:
    f.write("\n".join(lines))
no_coords = [v["name"] for v in venues.values() if v["lat"] is None]
palettes = len(load("team_colors.json")["teams"])
shapes_desc = ", ".join(f"{n} {k}" for k, n in sorted(shape_counts.items(), key=lambda kv: -kv[1]))
print(f"wrote {out}: {len(teams)} teams, {palettes} team palettes, {len(venues)} venues ({len(no_coords)} without coordinates)", file=sys.stderr)
print(f"  venue shapes: {shapes_desc}", file=sys.stderr)
