#!/usr/bin/env python3
"""Fill seed/venue_timezones.json: the IANA timezone of every seeded venue.

`venues.tz` is what turns a stored UTC `scheduled_start` back into the date the game was played
on where it was played. Search, the famous-game matcher and anything else that says "the local
date" need it. Only the MLB venues had one, because the MLB Stats API publishes it; the NFL and
NBA seed files carry none, so 126 of 295 venues were null and every evening game on the west
coast filed itself under the next day.

The zone comes from the coordinates, never from memory, with `timezonefinder` (offline, bundled
OpenStreetMap boundaries), so Phoenix gets America/Phoenix rather than America/Denver and a
London or Mexico City game gets its own zone.

  pip install timezonefinder
  python3 seed/scripts/fill_timezones.py            # resolve what is missing
  python3 seed/scripts/fill_timezones.py --sql      # print the UPDATE a migration needs
  python3 seed/scripts/fill_timezones.py --check    # print the sanity values

Then: python3 seed/scripts/build_seed_sql.py, which carries the column into supabase/seed.sql.
A venue already in the file with the same coordinates is skipped, so a rerun resolves nothing.
"""
import datetime, json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from venues import merged_venues  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TIMEZONES = os.path.join(ROOT, "seed", "venue_timezones.json")

# Checked by hand after the first run: the zones that are easy to get wrong.
SANITY = {
    "mlb-chase-field": "America/Phoenix",      # Arizona does not keep daylight time
    "mlb-coors-field": "America/Denver",
    "mlb-fenway-park": "America/New_York",
    "mlb-wrigley-field": "America/Chicago",
    "crypto-com-arena": "America/Los_Angeles",
    "ball-arena": "America/Denver",
    "rogers-centre": "America/Toronto",
    "chase-center": "America/Los_Angeles",
}


def load():
    if not os.path.exists(TIMEZONES):
        return {}
    with open(TIMEZONES, encoding="utf8") as f:
        return json.load(f)


def save(data):
    with open(TIMEZONES, "w", encoding="utf8") as f:
        json.dump(data, f, indent=1, sort_keys=True)
        f.write("\n")


def resolve(venues, known):
    from timezonefinder import TimezoneFinder

    finder = TimezoneFinder()
    today = datetime.date.today().isoformat()
    missing = []
    # merged_venues() is keyed by venue key.
    for v in venues.values():
        key, lat, lng = v["key"], v.get("lat"), v.get("lng")
        if lat is None or lng is None:
            missing.append(f"{key}: no coordinates")
            continue
        hit = known.get(key)
        # Coordinates are part of the record, so a venue that moves is resolved again.
        if hit and hit.get("lat") == lat and hit.get("lng") == lng:
            continue
        # timezone_at answers from the polygon the point is in; at_land falls back to the nearest
        # zone for a point the boundaries call water, which a coastal stadium can be.
        tz = finder.timezone_at(lat=lat, lng=lng) or finder.timezone_at_land(lat=lat, lng=lng)
        if not tz:
            missing.append(f"{key}: no zone at {lat},{lng}")
            continue
        known[key] = {"tz": tz, "lat": lat, "lng": lng, "resolved_on": today}
        save(known)
    return missing


def main():
    args = set(sys.argv[1:])
    venues = merged_venues()
    known = load()

    if "--sql" in args:
        print("-- Generated by seed/scripts/fill_timezones.py")
        for key in sorted(known):
            tz = known[key]["tz"].replace("'", "''")
            print(f"update public.venues set tz = '{tz}' where key = '{key}' and tz is null;")
        return

    if "--check" in args:
        for key, want in SANITY.items():
            got = known.get(key, {}).get("tz")
            mark = "ok " if got == want else "BAD"
            print(f"{mark} {key}: {got} (expected {want})")
        return

    missing = resolve(venues, known)
    zones = {}
    for entry in known.values():
        zones[entry["tz"]] = zones.get(entry["tz"], 0) + 1
    print(f"{len(known)} of {len(venues)} venues have a zone")
    for tz, n in sorted(zones.items(), key=lambda kv: -kv[1]):
        print(f"  {n:4d}  {tz}")
    for line in missing:
        print(f"  unresolved: {line}")


if __name__ == "__main__":
    main()
