-- ESPN numbers venues per sport: id 10660 is Gillette Stadium on the soccer scoreboard and Accor
-- Arena (Paris) on the basketball one. One shared `espn_venue_ids` map resolved New England's 2026
-- home matches to Paris on hosted (17 matches; local had none because its seed loaded in a different
-- order). Soccer ids now live under `provider_ids.espn_soccer_venue_ids`, generated here from
-- seed/mls_venues.json through seed/scripts/venues.py, and the matches go back to Foxborough.

update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4418"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4418"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4418"]'::jsonb)))) else '{}'::jsonb end where key = 'bank-of-america-stadium';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["1423"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["1423"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["1423"]'::jsonb)))) else '{}'::jsonb end where key = 'dignity-health-sports-park';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["1419"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["1419"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["1419"]'::jsonb)))) else '{}'::jsonb end where key = 'empower-field-at-mile-high';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["10660"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["10660"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["10660"]'::jsonb)))) else '{}'::jsonb end where key = 'gillette-stadium';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["5960"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["5960"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["5960"]'::jsonb)))) else '{}'::jsonb end where key = 'levis-stadium';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["1722"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["1722"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["1722"]'::jsonb)))) else '{}'::jsonb end where key = 'los-angeles-memorial-coliseum';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4485"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4485"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4485"]'::jsonb)))) else '{}'::jsonb end where key = 'lumen-field';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["7485"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["7485"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["7485"]'::jsonb)))) else '{}'::jsonb end where key = 'mercedes-benz-stadium';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["5146"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["5146"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["5146"]'::jsonb)))) else '{}'::jsonb end where key = 'mlb-citi-field';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4896"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4896"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4896"]'::jsonb)))) else '{}'::jsonb end where key = 'mlb-yankee-stadium';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["10143"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["10143"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["10143"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-10143';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["10421"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["10421"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["10421"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-10421';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["10661"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["10661"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["10661"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-10661';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["1417"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["1417"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["1417"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-1417';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["1418"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["1418"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["1418"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-1418';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["1451"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["1451"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["1451"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-1451';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["1764"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["1764"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["1764"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-1764';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["2242"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["2242"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["2242"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-2242';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["2266"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["2266"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["2266"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-2266';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["2731"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["2731"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["2731"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-2731';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["3262"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["3262"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["3262"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-3262';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["3278"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["3278"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["3278"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-3278';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["3714"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["3714"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["3714"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-3714';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["3869"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["3869"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["3869"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-3869';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4061"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4061"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4061"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-4061';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4087"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4087"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4087"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-4087';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4370"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4370"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4370"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-4370';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4373"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4373"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4373"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-4373';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4383"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4383"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4383"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-4383';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4385"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4385"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4385"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-4385';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4653"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4653"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4653"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-4653';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["4791"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["4791"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["4791"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-4791';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["6072"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["6072"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["6072"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-6072';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["6538"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["6538"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["6538"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-6538';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["6587"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["6587"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["6587"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-6587';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["6738"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["6738"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["6738"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-6738';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["6970"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["6970"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["6970"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-6970';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["6971"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["6971"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["6971"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-6971';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["7474"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["7474"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["7474"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-7474';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["7604"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["7604"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["7604"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-7604';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["7605"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["7605"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["7605"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-7605';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["7658"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["7658"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["7658"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-7658';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["8330"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["8330"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["8330"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-8330';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["8673"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["8673"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["8673"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-8673';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["8674"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["8674"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["8674"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-8674';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["8689"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["8689"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["8689"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-8689';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["8993"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["8993"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["8993"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-8993';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["9195"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["9195"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["9195"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-9195';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["9606"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["9606"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["9606"]'::jsonb)))) else '{}'::jsonb end where key = 'mls-espn-9606';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["3873"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["3873"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["3873"]'::jsonb)))) else '{}'::jsonb end where key = 'mt-bank-stadium';
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', '["1452"]'::jsonb) || case when (select count(*) from jsonb_array_elements_text(coalesce(provider_ids->'espn_venue_ids','[]'::jsonb)) e where e.value not in (select jsonb_array_elements_text('["1452"]'::jsonb))) > 0 then jsonb_build_object('espn_venue_ids', (select jsonb_agg(e.value) from jsonb_array_elements_text(provider_ids->'espn_venue_ids') e where e.value not in (select jsonb_array_elements_text('["1452"]'::jsonb)))) else '{}'::jsonb end where key = 'soldier-field';

-- A venue the MLS ingest created itself since the seed (`new_venues` in the daily job) carries the
-- old key with only soccer ids: rename it.
update public.venues set provider_ids = (provider_ids - 'espn_venue_ids') || jsonb_build_object('espn_soccer_venue_ids', provider_ids->'espn_venue_ids') where key like 'mls-espn-%' and provider_ids ? 'espn_venue_ids';

-- The misplaced matches: every MLS match at Accor Arena was a New England home match.
update public.games g set venue_id = (select id from public.venues where key = 'gillette-stadium')
  where g.sport_id = 'mls' and g.venue_id = (select id from public.venues where key = 'accor-arena');
