-- Coordinates, timezones and elevations for the MLS-only stadiums (Dean, 2026-09-22, decision 12).
-- 39 venues that had hosted an MLS match with no coordinates: 37 placed by OpenStreetMap Nominatim and
-- cross-checked against the Wikipedia infobox (all within 181 m), Q2 Stadium and RFK Stadium from
-- Wikipedia alone (Nominatim cannot place them). Zones from timezonefinder on those coordinates,
-- elevations from USGS EPQS and, for the four Canadian stadiums, Natural Resources Canada's CDEM
-- service (Open-Elevation's certificate had expired on the day). Sources per stadium: docs/verification.md. Nothing here is guessed.
-- Only rows still without a coordinate are touched, so a hand-corrected venue is never overwritten.

update public.venues set lat = 38.63132, lng = -90.21031, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 476), city = 'St. Louis, Missouri', country = 'USA' where key = 'mls-espn-10421' and lat is null;
update public.venues set lat = 39.11118, lng = -84.52223, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 534), city = 'Cincinnati, Ohio', country = 'USA' where key = 'mls-espn-8674' and lat is null;
update public.venues set lat = 38.86826, lng = -77.01261, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 17), city = 'Washington, District of Columbia', country = 'USA' where key = 'mls-espn-7604' and lat is null;
update public.venues set lat = 28.5411, lng = -81.38914, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 100), city = 'Orlando, Florida', country = 'USA' where key = 'mls-espn-6971' and lat is null;
update public.venues set lat = 49.27669, lng = -123.11201, tz = coalesce(tz, 'America/Vancouver'), elevation_ft = coalesce(elevation_ft, 30), city = 'Vancouver', country = 'Canada' where key = 'mls-espn-4370' and lat is null;
update public.venues set lat = 30.3877, lng = -97.7195, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 759), city = 'Austin, Texas', country = 'USA' where key = 'mls-espn-8673' and lat is null;
update public.venues set lat = 33.15422, lng = -96.83537, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 625), city = 'Frisco', country = 'USA' where key = 'mls-espn-7474' and lat is null;
update public.venues set lat = 29.75203, lng = -95.35234, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 35), city = 'Houston, Texas', country = 'USA' where key = 'mls-espn-4791' and lat is null;
update public.venues set lat = 36.13003, lng = -86.76594, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 483), city = 'Nashville, Tennessee', country = 'USA' where key = 'mls-espn-8993' and lat is null;
update public.venues set lat = 45.52153, lng = -122.69182, tz = coalesce(tz, 'America/Los_Angeles'), elevation_ft = coalesce(elevation_ft, 79), city = 'Portland, Oregon', country = 'USA' where key = 'mls-espn-4383' and lat is null;
update public.venues set lat = 32.78424, lng = -117.12239, tz = coalesce(tz, 'America/Los_Angeles'), elevation_ft = coalesce(elevation_ft, 58), city = 'San Diego, California', country = 'USA' where key = 'mls-espn-9195' and lat is null;
update public.venues set lat = 37.35131, lng = -121.92467, tz = coalesce(tz, 'America/Los_Angeles'), elevation_ft = coalesce(elevation_ft, 57), city = 'San Jose, California', country = 'USA' where key = 'mls-espn-6072' and lat is null;
update public.venues set lat = 40.73689, lng = -74.15026, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 11), city = 'Harrison, New Jersey', country = 'USA' where key = 'mls-espn-9606' and lat is null;
update public.venues set lat = 39.80595, lng = -104.89192, tz = coalesce(tz, 'America/Denver'), elevation_ft = coalesce(elevation_ft, 5201), city = 'Commerce City, Colorado', country = 'USA' where key = 'mls-espn-2731' and lat is null;
update public.venues set lat = 44.95314, lng = -93.16469, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 909), city = 'Saint Paul, Minnesota', country = 'USA' where key = 'mls-espn-6538' and lat is null;
update public.venues set lat = 40.58296, lng = -111.89329, tz = coalesce(tz, 'America/Denver'), elevation_ft = coalesce(elevation_ft, 4427), city = 'Sandy, Utah', country = 'USA' where key = 'mls-espn-3714' and lat is null;
update public.venues set lat = 39.12164, lng = -94.82335, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 964), city = 'Kansas City, Kansas', country = 'USA' where key = 'mls-espn-6587' and lat is null;
update public.venues set lat = 39.83291, lng = -75.37847, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 12), city = 'Chester, Pennsylvania', country = 'USA' where key = 'mls-espn-4061' and lat is null;
update public.venues set lat = 39.96836, lng = -83.01666, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 705), city = 'Columbus, Ohio', country = 'USA' where key = 'mls-espn-8689' and lat is null;
update public.venues set lat = 34.01277, lng = -118.28334, tz = coalesce(tz, 'America/Los_Angeles'), elevation_ft = coalesce(elevation_ft, 181), city = 'Los Angeles, California', country = 'USA' where key = 'mls-espn-7605' and lat is null;
update public.venues set lat = 43.63334, lng = -79.41856, tz = coalesce(tz, 'America/Toronto'), elevation_ft = coalesce(elevation_ft, 282), city = 'Toronto', country = 'Canada' where key = 'mls-espn-10143' and lat is null;
update public.venues set lat = 25.79245, lng = -80.26029, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 5), city = 'Miami, Florida', country = 'USA' where key = 'mls-espn-10661' and lat is null;
update public.venues set lat = 45.56309, lng = -73.55264, tz = coalesce(tz, 'America/Toronto'), elevation_ft = coalesce(elevation_ft, 131), city = 'Montreal', country = 'Canada' where key = 'mls-espn-3278' and lat is null;
update public.venues set lat = 37.43453, lng = -122.16199, tz = coalesce(tz, 'America/Los_Angeles'), elevation_ft = coalesce(elevation_ft, 65), city = 'Stanford, California', country = 'USA' where key = 'mls-espn-3869' and lat is null;
update public.venues set lat = 41.76481, lng = -87.80619, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 613), city = 'Bridgeview, Illinois', country = 'USA' where key = 'mls-espn-2266' and lat is null;
update public.venues set lat = 40.00947, lng = -82.99114, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 843), city = 'Columbus, Ohio', country = 'USA' where key = 'mls-espn-1417' and lat is null;
update public.venues set lat = 38.89, lng = -76.9719, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 10), city = 'Washington, District of Columbia', country = 'USA' where key = 'mls-espn-1418' and lat is null;
update public.venues set lat = 39.15178, lng = -77.31185, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 422), city = 'Boyds, Maryland', country = 'USA' where key = 'mls-espn-1451' and lat is null;
update public.venues set lat = 41.75961, lng = -72.61884, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 26), city = 'East Hartford, Connecticut', country = 'USA' where key = 'mls-espn-1764' and lat is null;
update public.venues set lat = 28.53904, lng = -81.40275, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 102), city = 'Orlando, Florida', country = 'USA' where key = 'mls-espn-2242' and lat is null;
update public.venues set lat = 36.16652, lng = -86.77131, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 397), city = 'Nashville, Tennessee', country = 'USA' where key = 'mls-espn-3262' and lat is null;
update public.venues set lat = 34.16135, lng = -118.16767, tz = coalesce(tz, 'America/Los_Angeles'), elevation_ft = coalesce(elevation_ft, 804), city = 'Pasadena, California', country = 'USA' where key = 'mls-espn-4087' and lat is null;
update public.venues set lat = 45.5578, lng = -73.55165, tz = coalesce(tz, 'America/Toronto'), elevation_ft = coalesce(elevation_ft, 98), city = 'Montreal', country = 'Canada' where key = 'mls-espn-4373' and lat is null;
update public.venues set lat = 39.12164, lng = -94.82335, tz = coalesce(tz, 'America/Chicago'), elevation_ft = coalesce(elevation_ft, 964), city = 'Kansas City, Kansas', country = 'USA' where key = 'mls-espn-4385' and lat is null;
update public.venues set lat = 40.73689, lng = -74.15026, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 11), city = 'Harrison, New Jersey', country = 'USA' where key = 'mls-espn-4653' and lat is null;
update public.venues set lat = 39.13112, lng = -84.51623, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 755), city = 'Cincinnati, Ohio', country = 'USA' where key = 'mls-espn-6738' and lat is null;
update public.venues set lat = 33.77248, lng = -84.39296, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 916), city = 'Atlanta, Georgia', country = 'USA' where key = 'mls-espn-6970' and lat is null;
update public.venues set lat = 38.98476, lng = -76.50708, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 29), city = 'Annapolis, Maryland', country = 'USA' where key = 'mls-espn-7658' and lat is null;
update public.venues set lat = 26.19324, lng = -80.16068, tz = coalesce(tz, 'America/New_York'), elevation_ft = coalesce(elevation_ft, 12), city = 'Fort Lauderdale, Florida', country = 'USA' where key = 'mls-espn-8330' and lat is null;
