-- Fan superlatives, second pass (Dean, 2026-09-17).
--
-- What was wrong: "Seen Carl Jones play" named the most seen player overall, who is usually a
-- stranger; "Biggest comeback, down 4" means different things in baseball and football; and there
-- were only ever three rows. What this does:
--
--   most_seen_favorite_player  the FAVOURITE player seen most; ties go to the one favourited first
--   biggest_comeback           chosen and described by win probability, with the deficit as fallback
--   largest_crowd              the highest games.attendance
--   highest_altitude           needs the new venues.elevation_ft; only from 1,000 ft up
--   farthest_venue, most_visited_venue   now carry a game_id, so every row can open a game
--
-- `most_seen_player` stays in the payload for builds already installed; the app stops showing it.
-- compute_user_stats is replaced from its latest definition (20260915000500_stats.sql) with only
-- the superlatives changed.

-- ---------------------------------------------------------------------------
-- Venue elevation
-- ---------------------------------------------------------------------------
alter table public.venues add column if not exists elevation_ft integer;

comment on column public.venues.elevation_ft is
  'Ground elevation in whole feet. USGS Elevation Point Query Service for the USA, Open-Elevation elsewhere; see seed/scripts/fill_elevations.py and docs/verification.md. Null when the venue has no coordinates.';

-- seed.sql carries the column from now on, but the local and hosted databases are already seeded
-- and never run it again. GENERATED by `python3 seed/scripts/fill_elevations.py --sql` from
-- seed/venue_elevations.json (fetched 2026-09-17); do not edit the values by hand.
update public.venues v set elevation_ft = e.elevation_ft
from (values
  ('acrisure-stadium', 724),
  ('alamodome', 662),
  ('allegiant-stadium', 2184),
  ('allianz-arena', 1608),
  ('arena-corinthians', 2575),
  ('arrowhead-stadium', 886),
  ('att-stadium', 567),
  ('bank-of-america-stadium', 708),
  ('caesars-superdome', 2),
  ('candlestick-park', 32),
  ('deutsche-bank-park', 381),
  ('dignity-health-sports-park', 49),
  ('dome-at-americas-center', 463),
  ('empower-field-at-mile-high', 5195),
  ('estadio-azteca', 7503),
  ('everbank-stadium', 4),
  ('ford-field', 603),
  ('foxboro-stadium', 313),
  ('georgia-dome', 997),
  ('giants-stadium', 9),
  ('gies-memorial-stadium', 732),
  ('gillette-stadium', 260),
  ('hard-rock-stadium', 9),
  ('highmark-stadium', 761),
  ('hubert-h-humphrey-metrodome', 845),
  ('huntington-bank-field', 583),
  ('huntington-bank-stadium', 829),
  ('husky-stadium', 32),
  ('lambeau-field', 620),
  ('levis-stadium', 13),
  ('lincoln-financial-field', 11),
  ('los-angeles-memorial-coliseum', 176),
  ('lucas-oil-stadium', 709),
  ('lumen-field', 18),
  ('maracana', 69),
  ('melbourne-cricket-ground', 39),
  ('mercedes-benz-stadium', 1017),
  ('metlife-stadium', 6),
  ('mile-high-stadium', 5210),
  ('mlb-american-family-field', 601),
  ('mlb-american-family-fields-of-phoenix', 1093),
  ('mlb-angel-stadium', 147),
  ('mlb-arvest-ballpark', 1310),
  ('mlb-autozone-park', 226),
  ('mlb-baycare-ballpark', 23),
  ('mlb-bb-t-ballpark', 717),
  ('mlb-bb-t-coastal-federal-field', 26),
  ('mlb-bristol-motor-speedway', 181),
  ('mlb-busch-stadium', 438),
  ('mlb-busch-stadium-i', 465),
  ('mlb-cacti-park-of-the-palm-beaches', 19),
  ('mlb-camelback-ranch', 1021),
  ('mlb-charlotte-sports-park', 11),
  ('mlb-chase-field', 1085),
  ('mlb-cheney-stadium', 329),
  ('mlb-chukchansi-park', 290),
  ('mlb-cinergy-field', 514),
  ('mlb-citi-field', 13),
  ('mlb-citizens-bank-park', 13),
  ('mlb-clover-park', 28),
  ('mlb-coca-cola-park', 362),
  ('mlb-comerica-park', 577),
  ('mlb-constellation-field', 78),
  ('mlb-coolray-field', 1085),
  ('mlb-cooltoday-park', 10),
  ('mlb-coors-field', 5180),
  ('mlb-daikin-park', 44),
  ('mlb-day-air-ballpark', 737),
  ('mlb-dr-pepper-ballpark', 700),
  ('mlb-durham-bulls-athletic-park', 362),
  ('mlb-ed-smith-stadium', 34),
  ('mlb-english-field', 2047),
  ('mlb-estadio-alfredo-harp-helu', 7336),
  ('mlb-fenway-park', 8),
  ('mlb-field-of-dreams', 994),
  ('mlb-fifth-third-field', 587),
  ('mlb-first-tennessee-park', 410),
  ('mlb-firstenergy-stadium', 239),
  ('mlb-five-county-stadium', 267),
  ('mlb-george-m-steinbrenner-field', 33),
  ('mlb-globe-life-field', 580),
  ('mlb-globe-life-park-in-arlington', 539),
  ('mlb-gocheok-sky-dome', 46),
  ('mlb-goodyear-ballpark', 951),
  ('mlb-great-american-ball-park', 490),
  ('mlb-harbor-park', 5),
  ('mlb-hiram-bithorn-stadium', 26),
  ('mlb-hohokam-stadium', 1250),
  ('mlb-huntington-park', 719),
  ('mlb-isotopes-park', 5137),
  ('mlb-jetblue-park', 24),
  ('mlb-joseph-p-riley-jr-ballpark', 11),
  ('mlb-journey-bank-ballpark', 521),
  ('mlb-kauffman-stadium', 888),
  ('mlb-las-vegas-ballpark', 3010),
  ('mlb-lecom-park', 21),
  ('mlb-lee-health-sports-complex', 16),
  ('mlb-loandepot-park', 9),
  ('mlb-loanmart-field', 1187),
  ('mlb-london-stadium', 46),
  ('mlb-louisville-slugger-field', 450),
  ('mlb-mgm-park', 22),
  ('mlb-milwaukee-county-stadium', 612),
  ('mlb-montgomery-riverwalk-stadium', 152),
  ('mlb-nationals-park', 23),
  ('mlb-nelson-w-wolff-municipal-stadium', 705),
  ('mlb-newbridge-bank-park', 801),
  ('mlb-olympic-stadium', 220),
  ('mlb-oneok-field', 704),
  ('mlb-oracle-park', 13),
  ('mlb-oriole-park-at-camden-yards', 17),
  ('mlb-pensacola-bayfront-stadium', 15),
  ('mlb-peoples-natural-gas-field', 1022),
  ('mlb-peoria-stadium', 1192),
  ('mlb-petco-park', 15),
  ('mlb-pnc-park', 725),
  ('mlb-progressive-field', 653),
  ('mlb-publix-field-at-joker-marchant-stadium', 160),
  ('mlb-rate-field', 596),
  ('mlb-redhawks-field-at-bricktown', 1178),
  ('mlb-regions-field', 586),
  ('mlb-rickwood-field', 550),
  ('mlb-robert-f-kennedy-memorial-stadium', 11),
  ('mlb-roger-dean-chevrolet-stadium', 15),
  ('mlb-route-66-stadium', 1311),
  ('mlb-sahlen-field', 589),
  ('mlb-salt-river-fields-at-talking-stick', 1295),
  ('mlb-scottsdale-stadium', 1240),
  ('mlb-shea-stadium', 13),
  ('mlb-sloan-park', 1174),
  ('mlb-smith-s-ballpark', 4233),
  ('mlb-southwest-university-park', 3743),
  ('mlb-surprise-stadium', 1201),
  ('mlb-sutter-health-park', 42),
  ('mlb-sydney-cricket-ground', 0),
  ('mlb-t-mobile-park', 12),
  ('mlb-target-field', 826),
  ('mlb-td-ameritrade-park', 1056),
  ('mlb-td-ballpark', 24),
  ('mlb-tempe-diablo-stadium', 1159),
  ('mlb-the-baseball-grounds-of-jacksonville', 7),
  ('mlb-the-dell-diamond', 662),
  ('mlb-the-diamond', 1277),
  ('mlb-the-stadium-at-the-espn-wide-world-of-sports', 103),
  ('mlb-tokyo-dome', 30),
  ('mlb-tropicana-field', 36),
  ('mlb-truist-park', 965),
  ('mlb-trustmark-park', 264),
  ('mlb-turner-field', 941),
  ('mlb-uniqlo-field-at-dodger-stadium', 502),
  ('mlb-victory-field', 706),
  ('mlb-werner-park', 1150),
  ('mlb-whataburger-field', 14),
  ('mlb-wrigley-field', 595),
  ('mlb-yankee-stadium', 14),
  ('mlb-yankee-stadium-i', 21),
  ('mountain-america-stadium', 1180),
  ('mt-bank-stadium', 10),
  ('nissan-stadium', 397),
  ('northwest-stadium', 196),
  ('oakland-coliseum', -17),
  ('paycor-stadium', 480),
  ('pontiac-silverdome', 870),
  ('ralph-wilson-stadium', 720),
  ('raymond-james-stadium', 36),
  ('rca-dome', 709),
  ('reliant-stadium', 50),
  ('rogers-centre', 299),
  ('san-diego-stadium', 53),
  ('santiago-bernabeu', 2362),
  ('sofi-stadium', 122),
  ('soldier-field', 586),
  ('stade-de-france', 187),
  ('state-farm-stadium', 1079),
  ('texas-stadium', 453),
  ('three-rivers-stadium', 731),
  ('tiger-stadium-lsu', 25),
  ('tottenham-hotspur-stadium', 43),
  ('twickenham-stadium', 66),
  ('us-bank-stadium', 846),
  ('veterans-stadium', 21),
  ('wembley-stadium', 197)
) as e (key, elevation_ft)
where v.key = e.key and v.elevation_ft is distinct from e.elevation_ft;

-- ---------------------------------------------------------------------------
-- The stats function, superlatives changed
-- ---------------------------------------------------------------------------
create or replace function public.compute_user_stats(p_user uuid)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_home_lat double precision;
  v_home_lng double precision;
  v_totals jsonb;
  v_overall jsonb;
  v_teams jsonb;
  v_pledge jsonb;
  v_stamps jsonb;
  v_super jsonb := '{}'::jsonb;
  v_moments jsonb;
  v_players_seen integer;
  v_streaks jsonb;
  r record;
  run integer := 0;
  longest_win integer := 0;
  longest_loss integer := 0;
begin
  select home_lat, home_lng into v_home_lat, v_home_lng from public.profiles where id = p_user;

  create temp table if not exists _ugr on commit drop as select * from public.user_game_results(p_user);
  truncate _ugr;
  insert into _ugr select * from public.user_game_results(p_user);

  select jsonb_build_object(
    'games', count(*) filter (where counted),
    'venues', count(distinct venue_id) filter (where counted),
    'states', count(distinct v.state) filter (where counted and v.state is not null),
    'countries', count(distinct coalesce(v.country, 'USA')) filter (where counted)
  ) into v_totals
  from _ugr u left join public.venues v on v.id = u.venue_id;

  select public.record_json(count(*) filter (where result = 'win'), count(*) filter (where result = 'loss'), count(*) filter (where result = 'tie'))
    into v_overall from _ugr;

  -- Team records: one tile per followed franchise (current team row carries the name).
  select coalesce(jsonb_agg(t order by t -> 'record' desc), '[]'::jsonb) into v_teams
  from (
    select jsonb_build_object(
      'franchise_id', f.franchise_id,
      'team_id', f.team_id,
      'name', f.name,
      'abbreviation', f.abbreviation,
      'sport_id', f.sport_id,
      'record', public.record_json(
        (select count(*) from _ugr u join public.teams rt on rt.id = u.rooting_team_id where rt.franchise_id = f.franchise_id and u.result = 'win'),
        (select count(*) from _ugr u join public.teams rt on rt.id = u.rooting_team_id where rt.franchise_id = f.franchise_id and u.result = 'loss'),
        (select count(*) from _ugr u join public.teams rt on rt.id = u.rooting_team_id where rt.franchise_id = f.franchise_id and u.result = 'tie'))
    ) as t
    from (
      select distinct on (t.franchise_id) t.franchise_id, t.id as team_id, t.name, t.abbreviation, t.sport_id
      from public.user_teams ut join public.teams t on t.id = ut.team_id
      where ut.user_id = p_user
      order by t.franchise_id, t.active desc
    ) f
  ) s;

  select jsonb_build_object(
    'record', public.record_json(count(*) filter (where u.result = 'win'), count(*) filter (where u.result = 'loss'), count(*) filter (where u.result = 'tie')),
    'vs_expected', round(coalesce(sum(case u.result when 'win' then 1 when 'tie' then 0.5 else 0 end - p.win_prob_at_pledge), 0)::numeric, 2)
  ) into v_pledge
  from _ugr u
  join public.pledges p on p.game_id = u.game_id and p.user_id = p_user and p.status = 'valid'
  where u.rooting_basis = 'pledge' and u.result is not null;

  select coalesce(jsonb_agg(s order by s -> 'visits' desc, s ->> 'first_visit'), '[]'::jsonb) into v_stamps
  from (
    select jsonb_build_object(
      'venue_id', v.id, 'name', v.name, 'city', v.city, 'state', v.state, 'country', v.country,
      'visits', count(*), 'first_visit', min(u.scheduled_start),
      'sports', (select jsonb_agg(distinct x.sport_id) from _ugr x where x.venue_id = v.id),
      'closed', v.closed_year is not null and v.closed_year <= extract(year from now())::integer,
      'lat', v.lat, 'lng', v.lng
    ) as s
    from _ugr u join public.venues v on v.id = u.venue_id
    where u.counted
    group by v.id
  ) q;

  -- Superlatives (each skips games missing the needed data). Every piece is wrapped in coalesce so a
  -- missing superlative never nulls the accumulator.
  v_super := v_super || coalesce((select jsonb_build_object('coldest', jsonb_build_object('game_id', game_id, 'value', temperature_f))
    from _ugr where counted and temperature_f is not null order by temperature_f asc, scheduled_start limit 1), '{}'::jsonb);
  v_super := v_super || coalesce((select jsonb_build_object('hottest', jsonb_build_object('game_id', game_id, 'value', temperature_f))
    from _ugr where counted and temperature_f is not null order by temperature_f desc, scheduled_start limit 1), '{}'::jsonb);
  v_super := v_super || coalesce((select jsonb_build_object('longest', jsonb_build_object('game_id', game_id, 'minutes', duration_minutes, 'periods', innings_or_periods))
    from _ugr where counted and (duration_minutes is not null or innings_or_periods is not null)
    order by coalesce(duration_minutes, 0) desc, coalesce(innings_or_periods, 0) desc limit 1), '{}'::jsonb);
  v_super := v_super || coalesce((select jsonb_build_object('highest_scoring', jsonb_build_object('game_id', game_id, 'total', home_score + away_score))
    from _ugr where counted and home_score is not null order by home_score + away_score desc, scheduled_start limit 1), '{}'::jsonb);
  v_super := v_super || coalesce((select jsonb_build_object('lowest_scoring', jsonb_build_object('game_id', game_id, 'total', home_score + away_score))
    from _ugr where counted and home_score is not null order by home_score + away_score asc, scheduled_start limit 1), '{}'::jsonb);

  -- Biggest comeback by the user's side, in a game they won.
  --
  -- "Down 4" means one thing in baseball and another in football, so the measure is win probability:
  -- the lowest chance the user's side had (from game_wp_timeline) in a game it went on to win, and
  -- only when that low point was below an even chance. The run or point deficit is still reported,
  -- and still decides the game when no won game has a timeline, which is every game without a
  -- Relive story. `deficit` is always a number because builds before this one print it as is.
  v_super := v_super || coalesce((
    select jsonb_build_object('biggest_comeback', jsonb_strip_nulls(jsonb_build_object(
      'game_id', c.game_id, 'sport_id', c.sport_id, 'deficit', greatest(coalesce(c.deficit, 0), 0),
      'low_win_prob', case when c.low_wp < 0.5 then c.low_wp end)))
    from (
      select u.game_id, u.sport_id, u.scheduled_start,
        (select round(min(case when u.rooting_team_id = u.home_team_id then w.home_wp else 1 - w.home_wp end), 4)
           from public.game_wp_timeline w where w.game_id = u.game_id) as low_wp,
        (select max(case when u.rooting_team_id = u.home_team_id then t.away_score - t.home_score else t.home_score - t.away_score end)
           from public.game_scoring_timeline t where t.game_id = u.game_id) as deficit
      from _ugr u
      where u.result = 'win'
    ) c
    where c.low_wp < 0.5 or c.deficit > 0
    -- A game whose low point is known outranks every game where it is not; among those, the lowest
    -- low point wins. With none, it is the largest deficit, as before.
    order by case when c.low_wp < 0.5 then 0 else 1 end,
             case when c.low_wp < 0.5 then c.low_wp end asc nulls last,
             c.deficit desc nulls last, c.scheduled_start
    limit 1), '{}'::jsonb);

  -- Largest crowd, from the box score's paid attendance.
  v_super := v_super || coalesce((select jsonb_build_object('largest_crowd', jsonb_build_object('game_id', game_id, 'attendance', attendance))
    from _ugr where counted and attendance is not null and attendance > 0 order by attendance desc, scheduled_start limit 1), '{}'::jsonb);

  -- Highest stadium. Only from 1,000 ft up, so it is a fun fact and never "you were at 20 feet".
  v_super := v_super || coalesce((
    select jsonb_build_object('highest_altitude', jsonb_build_object('venue_id', v.id, 'name', v.name, 'elevation_ft', v.elevation_ft, 'game_id', m.game_id))
    from (
      select venue_id, (array_agg(game_id order by scheduled_start desc))[1] as game_id
      from _ugr where counted and venue_id is not null group by venue_id
    ) m
    join public.venues v on v.id = m.venue_id
    where v.elevation_ft >= 1000
    order by v.elevation_ft desc, v.name limit 1), '{}'::jsonb);

  -- The favourite player you have seen most. Ties go to the one you favourited first, then by name.
  -- A favourite you have never seen is not a superlative, so no favourites seen means no key.
  v_super := v_super || coalesce((
    select jsonb_build_object('most_seen_favorite_player', jsonb_build_object('player_id', p.id, 'name', p.full_name, 'count', m.cnt))
    from (
      select up.player_id, up.created_at, count(*) as cnt
      from public.user_players up
      join public.game_appearances ga on ga.player_id = up.player_id
      join _ugr u on u.game_id = ga.game_id and u.counted
      where up.user_id = p_user
      group by up.player_id, up.created_at
    ) m join public.players p on p.id = m.player_id
    order by m.cnt desc, m.created_at asc, p.full_name asc limit 1), '{}'::jsonb);

  -- Kept for builds already installed, which read this key. The app no longer shows it: the most
  -- seen player overall is usually a stranger ("Carl Jones"), which is why the row above exists.
  v_super := v_super || coalesce((
    select jsonb_build_object('most_seen_player', jsonb_build_object('player_id', p.id, 'name', p.full_name, 'count', cnt))
    from (
      select ga.player_id, count(*) as cnt
      from _ugr u join public.game_appearances ga on ga.game_id = u.game_id
      where u.counted group by ga.player_id order by cnt desc, ga.player_id limit 1
    ) m join public.players p on p.id = m.player_id), '{}'::jsonb);

  v_super := v_super || jsonb_build_object('most_seen_by_team', coalesce((
    select jsonb_agg(x) from (
      select distinct on (f.franchise_id) jsonb_build_object('franchise_id', f.franchise_id, 'team_name', f.name, 'player_id', p.id, 'name', p.full_name, 'count', cnt) as x
      from (
        select distinct on (t.franchise_id) t.franchise_id, t.name from public.user_teams ut join public.teams t on t.id = ut.team_id where ut.user_id = p_user order by t.franchise_id, t.active desc
      ) f
      join lateral (
        select ga.player_id, count(*) as cnt
        from _ugr u join public.game_appearances ga on ga.game_id = u.game_id join public.teams gt on gt.id = ga.team_id
        where u.counted and gt.franchise_id = f.franchise_id group by ga.player_id order by cnt desc limit 1
      ) m on true
      join public.players p on p.id = m.player_id
    ) q), '[]'::jsonb));

  v_super := v_super || coalesce((
    select jsonb_build_object('most_visited_venue', jsonb_build_object('venue_id', v.id, 'name', v.name, 'visits', cnt, 'game_id', m.game_id))
    from (
      select venue_id, count(*) cnt, max(scheduled_start) last_at, (array_agg(game_id order by scheduled_start desc))[1] as game_id
      from _ugr where counted and venue_id is not null group by venue_id order by cnt desc, last_at desc limit 1
    ) m
    join public.venues v on v.id = m.venue_id), '{}'::jsonb);

  if v_home_lat is not null then
    v_super := v_super || coalesce((
      select jsonb_build_object('farthest_venue', jsonb_build_object('venue_id', v.id, 'name', v.name, 'km', round(d::numeric), 'game_id', m.game_id))
      from (
        select u.venue_id, public.distance_km(v_home_lat, v_home_lng, v.lat, v.lng) d, (array_agg(u.game_id order by u.scheduled_start desc))[1] as game_id
        from _ugr u join public.venues v on v.id = u.venue_id where u.counted and v.lat is not null
        group by u.venue_id, v.lat, v.lng
      ) m
      join public.venues v on v.id = m.venue_id
      order by d desc limit 1), '{}'::jsonb);

    v_super := v_super || coalesce((
      select jsonb_build_object('most_miles_team', jsonb_build_object('franchise_id', m.franchise_id, 'team_name', m.name, 'km', round(m.km::numeric)))
      from (
        select rt.franchise_id, min(rt.name) as name, sum(public.distance_km(v_home_lat, v_home_lng, v.lat, v.lng)) as km
        from _ugr u join public.teams rt on rt.id = u.rooting_team_id join public.venues v on v.id = u.venue_id
        where u.counted and v.lat is not null and u.rooting_team_id <> u.home_team_id
        group by rt.franchise_id
      ) m order by m.km desc limit 1), '{}'::jsonb);
  end if;

  v_super := v_super || coalesce((select jsonb_build_object('first_game', jsonb_build_object('game_id', game_id, 'date', scheduled_start))
    from _ugr where counted order by scheduled_start asc limit 1), '{}'::jsonb);

  -- Streaks.
  for r in select result from _ugr where result is not null order by scheduled_start loop
    if r.result = 'win' then run := case when run > 0 then run + 1 else 1 end;
    elsif r.result = 'loss' then run := case when run < 0 then run - 1 else -1 end;
    else run := 0;
    end if;
    longest_win := greatest(longest_win, run);
    longest_loss := greatest(longest_loss, -run);
  end loop;
  v_streaks := jsonb_build_object('longest_win', longest_win, 'longest_loss', longest_loss, 'current', run);

  select coalesce(jsonb_agg(jsonb_build_object('type', type, 'count', cnt) order by cnt desc), '[]'::jsonb) into v_moments
  from (
    select e.type, count(*) cnt
    from _ugr u join public.game_events e on e.game_id = u.game_id
    where u.counted and e.type <> 'home_run'
    group by e.type
  ) m;

  select count(distinct ga.player_id) into v_players_seen
  from _ugr u join public.game_appearances ga on ga.game_id = u.game_id where u.counted;

  return jsonb_build_object(
    'totals', v_totals,
    'overall', v_overall,
    'teams', v_teams,
    'pledge', coalesce(v_pledge, jsonb_build_object('record', public.record_json(0, 0, 0), 'vs_expected', 0)),
    'stamps', v_stamps,
    'superlatives', v_super,
    'streaks', v_streaks,
    'moments', v_moments,
    'players_seen', coalesce(v_players_seen, 0),
    'computed_at', now()
  );
end;
$$;

revoke all on function public.compute_user_stats(uuid) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Favourites feed a superlative now, so changing them has to refresh the cache, exactly as
-- changing favourite teams does. An upsert of a player already favourited is an update and
-- changes nothing, so only insert and delete matter.
-- ---------------------------------------------------------------------------
create or replace function public.user_players_after_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.refresh_user_stats(coalesce(new.user_id, old.user_id));
  return null;
end;
$$;

drop trigger if exists user_players_after_change on public.user_players;
create trigger user_players_after_change
  after insert or delete on public.user_players
  for each row execute function public.user_players_after_change();

-- ---------------------------------------------------------------------------
-- Recompute every cached payload, so nobody waits for their next logged game to see the new rows.
-- ---------------------------------------------------------------------------
do $$
declare
  u uuid;
begin
  for u in select user_id from public.user_stats_cache loop
    perform public.refresh_user_stats(u);
  end loop;
end;
$$;
